[project]
name = "mosqlimate-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain>=0.3.20",
    "langchain-ollama>=0.2.3",
    "pydantic>=2.10.6",
    "requests>=2.32.3",
    "typing>=3.10.0.0",
]
